# permissions for end users to edit poolers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pooler-editor-role
rules:
- apiGroups:
  - postgresql.acceldata.io
  resources:
  - poolers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.acceldata.io
  resources:
  - poolers/status
  verbs:
  - get
